name: Go CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build, Lint, and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23.4 

      - name: Install dependencies
        run: go mod tidy

      - name: Install GolangCI-Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54.2

      - name: Run golangci-lint
        run: golangci-lint run