name: Lint
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.1'

      - name: Verify Go Environment
        run: |
          go version
          go env

      - name: Install golangci-lint
        env:
          GOLANGCI_LINT_VERSION: v1.52.0
        run: |
          curl -sSfL https://github.com/golangci/golangci-lint/releases/download/${GOLANGCI_LINT_VERSION}/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64.tar.gz | tar -xz -C /tmp
          sudo mv /tmp/golangci-lint-${GOLANGCI_LINT_VERSION}-linux-amd64/golangci-lint /usr/local/bin/

      - name: Run golangci-lint
        run: golangci-lint run --config .golangci.yml
